CREATE TABLE IF NOT EXISTS links (
  slug TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE links ADD COLUMN IF NOT EXISTS owner TEXT;

CREATE INDEX IF NOT EXISTS links_owner_idx ON links (owner);

CREATE TABLE IF NOT EXISTS clicks (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL REFERENCES links(slug) ON DELETE CASCADE,
  clicked_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS clicks_slug_idx ON clicks (slug);
CREATE INDEX IF NOT EXISTS clicks_clicked_at_idx ON clicks (clicked_at);
